Добавляет наставника
htmlacademy-htmlcss/1866847-sedona-35 pull request #1
Opened 2022-09-19 20:16 UTC by AntonKld

2022-09-20 03:39 UTC, Dima-Dim requested changes

2022-09-20 03:39 UTC, Dima-Dim commented on Readme.md
> +* Наставник: `Дмитрий Гуляев`. (https://htmlacademy.ru/profile/dima)
Сейчас это выглядит вот так:
https://github.com/htmlacademy-htmlcss/1866847-sedona-35/blob/0aebc367378258ba4148b4c2db55e2bc16a0631e/Readme.md
Нужно немного поправить чтобы ссылкой были имя и фамилия.

2022-09-20 09:24 UTC, AntonKld commented on Readme.md
> +* Наставник: `Дмитрий Гуляев`. (https://htmlacademy.ru/profile/dima)
Добрый день. Вот так?

2022-09-21 06:08 UTC, Dima-Dim commented on Readme.md
> +* Наставник: `Дмитрий Гуляев`. (https://htmlacademy.ru/profile/dima)
Да, так https://github.com/htmlacademy-htmlcss/1866847-sedona-35/blob/212f8ebde0ab5ae74318de26a4ffbb5c3f524f8f/Readme.md лушче.

2022-09-21 14:18 UTC, merged