Базовая стилизация
htmlacademy-htmlcss/1866847-sedona-35 pull request #4
Opened 2022-10-06 09:04 UTC by AntonKld

2022-10-07 04:04 UTC, Dima-Dim requested changes
images/home-page/Vector.svg https://up.htmlacademy.ru/htmlcss/35/criteries#PROJ-03
images/home-page/white-hero.svg - изображение белого прямоуголника?
images/home-page/white.svg - второе изображение белого прямоуголника, такого же, но с другим названием? :)

2022-10-07 04:04 UTC, Dima-Dim commented on catalog.html
>        <header class="inner-header">
Тег `header` стал вложенным, значит ему нужно добавить отступов.

2022-10-07 04:04 UTC, Dima-Dim commented on catalog.html
> +        <h3 class="newsletter-title-subscription">
Тоже вложенность добилась, а отступы нет.

2022-10-07 04:04 UTC, Dima-Dim commented on catalog.html
> +        </section>
Тут вообще всё в обратную сторону уехало.

2022-10-07 04:04 UTC, Dima-Dim commented on styles/styles.css
> +button {
https://up.htmlacademy.ru/htmlcss/35/criteries#CSS-02

2022-10-07 04:04 UTC, Dima-Dim commented on styles/styles.css
> +display: block;
В css тоже хорошо бы соблюдать отступы.

2022-10-07 04:04 UTC, Dima-Dim commented on styles/styles.css
> +  background-color: #82B3D3;;
Хватит и 1-ой `;`

2022-10-07 04:04 UTC, Dima-Dim commented on catalog.html
> +        <div class="newsletter">
Для чего тут `div` с таким же классом как и у `section`?

2022-10-08 13:53 UTC, Dima-Dim requested changes

2022-10-08 13:53 UTC, Dima-Dim commented on catalog.html
> +            <img class="main-header-logo" src="images/home-page/logo-sedona.svg" width="140" height="70"
Логотип не является частью навигации.

2022-10-08 13:53 UTC, Dima-Dim commented on catalog.html
> +                  Поиск
Поиск тоже не навигация.

2022-10-08 13:53 UTC, Dima-Dim commented on index.html
> +          <h2 class="visually-hidden">
Если ниже появился заголовок, то скрытый можно убрать.

2022-10-08 13:53 UTC, Dima-Dim commented on styles/styles.css
> +button {
Почему не исправлено?

2022-10-08 13:53 UTC, Dima-Dim commented on styles/styles.css
> +  Width: 1200px;
`Width` -> `width`

2022-10-08 13:53 UTC, Dima-Dim commented on styles/styles.css
> +  Height: 485px;
`Height` - > `height`

2022-10-08 13:53 UTC, Dima-Dim commented on styles/styles.css
> +  background-image: url(../images/home-page/Subscribe.jpg);
`Subscribe.jpg` -> https://up.htmlacademy.ru/htmlcss/35/criteries#PROJ-03

2022-10-08 13:53 UTC, Dima-Dim commented on styles/styles.css
> +  height: 52px;
Увеличение количества контента приведёт его выпаданию из контейнера.

2022-10-08 13:53 UTC, Dima-Dim commented on styles/styles.css
> +  background-color: #ffffff;
Делай единообразно, или большие буквы в цветах везде или маленькие.

2022-10-08 19:37 UTC, AntonKld commented on styles/styles.css
> +button {
Я понял что это глобальный селектор. Включил видео обучающее  "Барбершоп. Базовая стилизация главной страницы", там писали button. Вот запутался почему там сделали.

2022-10-11 03:20 UTC, Dima-Dim commented on styles/styles.css
> +button {
У тебя это не класс, а тег.

2022-10-11 04:21 UTC, Dima-Dim commented on styles/styles.css
> +.button-blue {
Если дизайнер решить поменять цвета будешь менять название классов? Не нужно давать классам названия на основании того как оно выглядят, выглядеть они могут по разному в разное время. Лучше использовать назначение элементов.

2022-10-11 04:21 UTC, Dima-Dim commented on styles/styles.css
> +  height: 52px;
Ограничение высоты приведёт к проблемам при переполнении.

2022-10-11 04:21 UTC, merged